apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-scale
spec:
  name: deployment
  replicas: 1
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: seldonio/mock_classifier:1.5.0
                name: classifier
      graph:
        children: []
        endpoint:
          type: REST
        name: classifier
        type: MODEL
      name: example
